### ISSUE TITLE
iframe URL 404s

### ISSUE THREAD

**Issue by leanne2** [storybooks/storybook-deployer#56]
I have deployed this repo https://github.com/leanne1/swatch-book/ to GH pages but the Storybook iframe 404s: https://leanne1.github.io/swatch-book/

The iframe src is https://leanne1.github.io/swatch-book/iframe.html? which does not exist. So whilst the Storybook UI deploys, my repo demo does not. I followed the simple steps in the README. No custom config. 

Any help on getting this working would be appreciated!

**Comment by klaidman** [comment]
I'm having the same issue. Storybook runs fine locally, but 404s on iframe.html either when built as a  static site, or when deployed to gh-pages.

**Comment by Neilpoulin** [comment]
I'm also getting this problem, however, I only run into it when I deploy to GH Pages via CircleCI. 

In both cases, I execute a yarn script: 
`yarn deploy-storybook --ci`
which in turns executes 
`storybook-to-ghpages --out=dist_storybook`

Here are the files that get uploaded when using CircleCI:
![image](https://user-images.githubusercontent.com/802410/53068156-a932e580-3494-11e9-881b-8079c8dcfe00.png)

When I run the same command locally on my dev machine, this is what makes it into GitHub (and the storybook works on the github.io url)
![image](https://user-images.githubusercontent.com/802410/53068203-d97a8400-3494-11e9-9849-c835665e1e01.png)

I can verify that I have my `GH_TOKEN` set in CircleCI and that I am able to push code

**Comment by AsukaSong** [comment]
any progress?

**Comment by shilman** [comment]
Just merged this, not sure if it's related: https://github.com/storybooks/storybook/pull/5947

**Comment by Neilpoulin** [comment]
Yeah, actually. I got my deployments to work by pre-building the storybook assets and deploying in a separate step using the ` --existing-output-dir` flag. 

In case it's helpful, here is my CircleCI config (at least the job aliases) and my scripts in package.json

config.yml (excerpt)
```yaml
  - &build-storybook-steps
    - checkout
    - restore_cache: *restore-root-dependencies
    - restore_cache: *restore-functions-dependencies
    - run:
        name: update npm and yarn
        command: "sudo npm install -g npm@latest && sudo npm install -g yarn@latest"
    - add_ssh_keys:
        fingerprints:
          - "xxxxx"
    - run: yarn build-storybook
    - run: ls dist_storybook
    - run:
        name: Check for iframe.html
        command: |
          if [ ! -f dist_storybook/iframe.html ]; then
            echo "iframe.html File not found!"
            exit 1
          fi
    - run: *fail_notification
  - &deploy-storybook-steps
    - checkout
    - restore_cache: *restore-root-dependencies
    - restore_cache: *restore-functions-dependencies
    - add_ssh_keys:
        fingerprints:
          - "xxxx"
    - run: yarn build-storybook
    - run: ls dist_storybook
    - run:
        name: Check for iframe.html
        command: |
          if [ ! -f dist_storybook/iframe.html ]; then
            echo "iframe.html File not found!"
            exit 1
          fi
    - run: yarn deploy-existing-storybook-ci

    - run: *fail_notification

```

package.json scripts (excerpt):
```json
{
"scripts": {
  
  "build-storybook": "yarn run config:get && build-storybook -c .storybook -o dist_storybook",
  "deploy-existing-storybook-ci": "yarn run config:get && storybook-to-ghpages --out=dist_storybook --existing-output-dir=dist_storybook --ci",
 
}
```
