### ISSUE TITLE
Instructions For CircleCI

### ISSUE THREAD

**Issue by LukeAskew** [storybooks/storybook-deployer#59]
Leaving this here for anyone struggling to get Storybook + CircleCI to work.

## 1. Setup SSH keys

1. Create a key per [these instructions](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). Note that CircleCI requires the PEM format, so the command to generate a key is `ssh-keygen -m PEM -t rsa -b 4096 -C "your_email@example.com"`
2. Add the public key to your project in Github https://github.com/{YOU}/{YOUR_PROJECT}/settings/keys
3. Add the private key to your CircleCI project https://circleci.com/gh/{YOU}/{YOUR_PROJECT}/edit#ssh

## 2. Update CircleCI project settings

1. Per [this article](https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests), turn off "Pass secrets to builds from forked pull requests" in your project's Advanced Settings https://circleci.com/gh/brightwheel/casa/edit#advanced-settings

## 3. Update `.circleci/config.yml`

1. Add new write-enabled ssh key to your job using the `add_ssh_keys` setting https://circleci.com/docs/2.0/add-ssh-key/
2. Add branch filters to your workflow to prevent CircleCI from building when `gh-pages` gets committed to.

Here's my config for reference:

```yml
version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0

commands:
  install_dependencies:
    ...
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'YOUR FINGERPRINT HERE'

jobs:
  ...
    deploy:
      executor: node
      steps:
        - set_deploy_key
        - checkout
        - install_dependencies
        - run:
            name: Deploy
            command: yarn deploy

workflows:
  deploy:
    jobs:
      - lint:
          filters:
            branches:
              ignore: 'gh-pages'
      - test:
          filters:
            branches:
              ignore: 'gh-pages'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
            - test
```
