### ISSUE TITLE
Error when run yarn deploy-storybook --ci in CircleCi

### ISSUE THREAD

**Issue by rafaelmusetti** [storybooks/storybook-deployer#63]
Hey guys,

I'm having an error while trying to deploy with CircleCi.

I don't know what's happening, because the problem began to appear now, and before that, it was already working.

my config:
```yaml
version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch
    environment:
      TZ: "/usr/share/zoneinfo/America/Sao_Paulo"
    steps:
      - checkout # special step to check out source code to working directory
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https
      - run: curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install yarn && yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run React Tests
          command: yarn jest --no-cache --runInBand

  deploy:
    docker:
      - image: circleci/node:12.2.0
    environment:
     GH_TOKEN: "MY_GH_TOKEN"
     NPM_TOKEN: "MY_NPM_TOKEN"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https
      - run: curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install yarn && yarn
      - run:
          name: Deploy Storybook
          command: yarn deploy-storybook --ci

  release:
    docker:
      - image: circleci/node:9-stretch
    environment:
     GH_TOKEN: "MY_GH_TOKEN"
     NPM_TOKEN: "MY_NPM_TOKEN"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https
      - run: curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install yarn && yarn
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - deploy:
          requires:
              - build
      - release:
          requires:
            - build
```

This is the error:
![circleCi](https://user-images.githubusercontent.com/12259796/58640845-51481e00-82d0-11e9-97ab-076324256d5a.png)

Can someone help me?
